export enum SocketCommunicationType {
  GAME = 1,
  CHAT = 2,
  CONNECTION = 3,
  FRIEND = 4,
  GAME_INVITATION = 5,
  GAME_START = 6,
  CHESS_BOARD = 7,
  CONNECT_BOARD = 8,
  CHESS_MOVEMENTS = 9,
  CONNECT4_MOVEMENTS = 10,
  END_GAME = 11,
  DRAW_REQUEST = 12,
  REMATCH_REQUEST = 13,
  SURRENDER = 14,
  REMATCH_DECLINED = 15,
  DRAW = 16,

}
